<?php
/**
 * Using Mobile Detect to return a json object for ajax calls
 **/
require_once "mobile_detect.php";

function mobile_detect_init() {
  if (drupal_is_front_page()) {
    drupal_add_js(drupal_get_path('module', 'mobile_detect') . '/mobile_detect.js');
  }
}

function mobile_detect_url_outbound_alter(&$path, &$options, $original_path) {
  if(!isset($options["query"]["m"]) && $options['external'] != TRUE) {
    if(isset($_GET["m"])) {
      array_push($options["query"], array("m" => $_GET["m"]));
    }
    else {
      $m_detect = new Mobile_Detect();
      array_push($options["query"], array("m" => $m_detect->isMobile()?1:0));
    }
  }
}

function mobile_detect_preprocess_page(&$variables) {
  if (drupal_is_front_page()) {
    $m_detect = new Mobile_Detect();
    // detects mobile devices excluding tablets
    $variables["mobile"] = $m_detect->isMobile();
    // $_COOKIE["mobile"] holds the version of the site to be displayed, 1 =  mobile, 0 = desktop.
    // Assume mobile version on mobile device as default
    if(!isset($_GET["m"])) {
      $_GET["m"] = 1;
    }
    
    $viewport = array(
      '#type' => 'html_tag',
      '#tag' => 'meta',
      '#attributes' => array(
        'name' =>  'viewport',
        'content' =>  'width=device-width, initial-scale=1, maximum-scale=1'
      )
    );
    if ($variables["mobile"] && ($_GET["m"] == 1)) {
      drupal_add_html_head($viewport, 'viewport');
    }
  }
}
